// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeJkLtAgsZPhbfjMEWEhb3MzJDYkUETdI',
    appId: '1:427726862589:web:788e86609fe3808931a694',
    messagingSenderId: '427726862589',
    projectId: 'flutter-exd',
    authDomain: 'flutter-exd.firebaseapp.com',
    storageBucket: 'flutter-exd.appspot.com',
    measurementId: 'G-VMEC4VE7E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyDPeGW_B6jBVk2C308FsiSBZqZm7akiY',
    appId: '1:427726862589:android:40c765a8887968d831a694',
    messagingSenderId: '427726862589',
    projectId: 'flutter-exd',
    storageBucket: 'flutter-exd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB208QLHeSsu-HLvMmiVfR9YcDLHtRymDU',
    appId: '1:427726862589:ios:19ff9453ac37970731a694',
    messagingSenderId: '427726862589',
    projectId: 'flutter-exd',
    storageBucket: 'flutter-exd.appspot.com',
    iosClientId: '427726862589-5crmb3dqrka4g2932ll509nb62sn5139.apps.googleusercontent.com',
    iosBundleId: 'com.example.exdFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB208QLHeSsu-HLvMmiVfR9YcDLHtRymDU',
    appId: '1:427726862589:ios:19ff9453ac37970731a694',
    messagingSenderId: '427726862589',
    projectId: 'flutter-exd',
    storageBucket: 'flutter-exd.appspot.com',
    iosClientId: '427726862589-5crmb3dqrka4g2932ll509nb62sn5139.apps.googleusercontent.com',
    iosBundleId: 'com.example.exdFlutterProject',
  );
}
